---
title: "Titre du projet"  
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    highlight: kate
    number_sections: TRUE
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE) #Activer le cache des chunks pour accélérer les recompilations
options("install.lock"=FALSE) #Désactiver le verrouillage d’installation des packages
setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) ## configure le chemin du dossier automatiquement
```

**JAOUEN Denis - GEINDRE Colin**

[**Master 1 MAS - Université de Rennes**](https://eco.univ-rennes.fr/master-mathematiques-appliquees-statistique) et [**Master 1 MAS - Université Rennes 2**](https://formations.univ-rennes2.fr/fr/formations/master-37/master-mention-mathematiques-appliquees-statistique-parcours-sciences-des-donnees-intelligence-artificielle-JFTJBMKM.html)

[Pensez à numéroter vos tables et graphiques, cela vous permet de faire des rappels dans votre texte. Attention également au titre et à la bonne définition des axes. Chaque graphique est commenté, il est parfois préférable de les regrouper au sein d'une même fenêtre pour que le rapport soit plus agréable à lire. N'hésitez pas à faire des sélections de graphiques intéressants plutôt que de les présenter d'une manière mécanique. Il ne faut pas utiliser le code de vos variables dans vos commentaires mais revenir sur leur signification.]{style="color:red;"}

# Introduction

Depuis trop longtemps, l'indice de développement d'un pays a été calculé sur des indices économiques (capitalistes) : PIB, croissance, taux d'emploi, etc. Ce choix n'est pas neutre, il sert un système particulier qui ne met pas l'humain ou l'environnement au coeur de ses priorités. Nous voulons avec cette étude poser la première pierre d'une réflexion sur de meilleures méthodollogies d'évaluation du développement, axées sur le bonheur, mais aussi le respect de notre environnement, de la biodiversité, etc.

Plusieurs études existent qui traitent du bonheur des populations. Une des plus célèbres est le world happiness report. Nous avons voulu tenter de comprendre comme cet indice de bonheur est corrélé / constraint par différents facteurs socio-économiques. En particulier voir si le PIB et la croissance sont de bons indicateurs, remettre en cause le paradigme si ce n'est pas le cas.

Hypothèse : le bonheur peut être prédit / calculé à partir de données socio économiques. Lesquelles ? A quel degré ? Y a t il des pays singuliers de part leur comportement sur ces données ? Des différences en fonction des groupes de pays ? OCDE, OPEP, OTAN ?

Plan :

-   Récupération des données

-   Traitement des données

-   Statistiques descriptives

-   Comparaison de modèles

-   Conclusion statistiques

# Cadre méthodologique

Le cadre méthodologique général est celui de la régression linéaire, avec une estimation des moindre carré ordinaire. En fonction des données, des corrections éventuelles (white, MCG, etc.) pourront être envisagées. Pour chaque partie, une méthodologie plus précise sera discutée.

# **Analyse des données**

## Cadre des données

Nous avons tenté d'avoir le cadre le plus global possible. Ainsi nous étudions les pays du monde entier, en particulier les 147 référencés par le world happiness report. En fonction des données acquises, certains pays peuvent être exclu, d'autres peuvent être utilisés pour d'éventuelles prédictions.

Nous traitons des données allant de 1789 à 2024, nous avons choisi de traiter simultanément plusieurs années, de comparer les modèles pour tirer des conclusions les plus larges possibles.

expliquer les variables utilisées, les unités et les sources + Faire un tableau récapitulatif

| Code de la série | Définition      |  Unité   |          Source |
|:-----------------|-----------------|:--------:|----------------:|
| Aligné à gauche  | Aligné à gauche | ce texte | Aligné à droite |
| Aligné à gauche  | Aligné à gauche |   est    | Aligné à droite |
| Aligné à gauche  | Aligné à gauche |  centré  | Aligné à droite |

## Prétraitement et nettoyage des données

-   Sélection d'individus : données manquantes

    -   moyenne glissante ?

    -   suppression d'individus ?

-   Sélection des variables

## Analyse descriptive univariée des données

Vous devez décrire les données utilisées dans la modélisation, après nettoyage.

-   Tableau de statistiques descriptives = données quantitatives / catégorielles

-   Box plot / histogramme / ... : chaque graphique doit

## Analyse descriptive bivariée des données

Vous devez décrire vos données vis à vis de votre variable à expliquer

-   corrélation vis à vis de Y

-   nuage de point vis à vis de Y

-   Corrélation entre les variables explicatives

# **Analyse et discussion des résultats**

## Modélisation principale

Présentation et interprétation des résultats obtenus : utiliser un tableau récapitulatif des modèles principaux testés

## Robustesse des résultats

Hypothèses des MCO - nomalités / hétéroscédasticité / ...

## Analyses complémentaires

-   Transformation de variables / effets non linéaires

-   Changement structurel

-   Effets croisés de variables

# **Conclusion générale et perspectives**

Rappel de la problématique et de la méthodologie

Synthèse des résultats principaux

Contributions du mémoire, apports scientifiques et/ou applicatifs

Perspectives d’amélioration ou de recherche future

possible sources d'erreur : mauvaises mesures des données, simultanéité, variables omises

# Bibliographie - Source des données
