<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>La source du bonheur</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="rendu_files/libs/clipboard/clipboard.min.js"></script>
<script src="rendu_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="rendu_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="rendu_files/libs/quarto-html/popper.min.js"></script>
<script src="rendu_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="rendu_files/libs/quarto-html/anchor.min.js"></script>
<link href="rendu_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="rendu_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="rendu_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="rendu_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="rendu_files/libs/bootstrap/bootstrap-50d1c276428054b407166721b449f8cf.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#plan" id="toc-plan" class="nav-link" data-scroll-target="#plan">Plan</a></li>
  <li><a href="#cadre-méthodologique" id="toc-cadre-méthodologique" class="nav-link" data-scroll-target="#cadre-méthodologique">Cadre méthodologique</a>
  <ul class="collapse">
  <li><a href="#modèle-de-régression" id="toc-modèle-de-régression" class="nav-link" data-scroll-target="#modèle-de-régression">Modèle de régression</a></li>
  <li><a href="#corrections-et-transformations-de-variables" id="toc-corrections-et-transformations-de-variables" class="nav-link" data-scroll-target="#corrections-et-transformations-de-variables">Corrections et transformations de variables</a></li>
  </ul></li>
  <li><a href="#analyse-des-données" id="toc-analyse-des-données" class="nav-link" data-scroll-target="#analyse-des-données">Analyse des données</a>
  <ul class="collapse">
  <li><a href="#cadre-des-données" id="toc-cadre-des-données" class="nav-link" data-scroll-target="#cadre-des-données">Cadre des données</a></li>
  <li><a href="#prétraitement-et-nettoyage-des-données" id="toc-prétraitement-et-nettoyage-des-données" class="nav-link" data-scroll-target="#prétraitement-et-nettoyage-des-données">Prétraitement et nettoyage des données</a></li>
  <li><a href="#analyse-descriptive-univariée-des-données" id="toc-analyse-descriptive-univariée-des-données" class="nav-link" data-scroll-target="#analyse-descriptive-univariée-des-données">Analyse descriptive univariée des données</a>
  <ul class="collapse">
  <li><a href="#analyse-de-chaque-variable-explicative" id="toc-analyse-de-chaque-variable-explicative" class="nav-link" data-scroll-target="#analyse-de-chaque-variable-explicative">Analyse de chaque variable explicative</a></li>
  </ul></li>
  <li><a href="#analyse-descriptive-bivariée-des-données" id="toc-analyse-descriptive-bivariée-des-données" class="nav-link" data-scroll-target="#analyse-descriptive-bivariée-des-données">Analyse descriptive bivariée des données</a></li>
  </ul></li>
  <li><a href="#analyse-et-discussion-des-résultats" id="toc-analyse-et-discussion-des-résultats" class="nav-link" data-scroll-target="#analyse-et-discussion-des-résultats"><strong>Analyse et discussion des résultats</strong></a>
  <ul class="collapse">
  <li><a href="#modélisation-principale" id="toc-modélisation-principale" class="nav-link" data-scroll-target="#modélisation-principale">Modélisation principale</a></li>
  <li><a href="#modélisation-avancée-et-sélection-de-variables" id="toc-modélisation-avancée-et-sélection-de-variables" class="nav-link" data-scroll-target="#modélisation-avancée-et-sélection-de-variables">Modélisation avancée et sélection de variables</a>
  <ul class="collapse">
  <li><a href="#traitement-de-la-multicolinéarité" id="toc-traitement-de-la-multicolinéarité" class="nav-link" data-scroll-target="#traitement-de-la-multicolinéarité">Traitement de la multicolinéarité</a></li>
  <li><a href="#sélection-de-variables-stepwise-par-aic" id="toc-sélection-de-variables-stepwise-par-aic" class="nav-link" data-scroll-target="#sélection-de-variables-stepwise-par-aic">Sélection de variables (Stepwise par AIC)</a></li>
  <li><a href="#test-de-non-linéarités-et-dinteractions" id="toc-test-de-non-linéarités-et-dinteractions" class="nav-link" data-scroll-target="#test-de-non-linéarités-et-dinteractions">Test de non-linéarités et d’interactions</a></li>
  <li><a href="#choix-du-modèle-final" id="toc-choix-du-modèle-final" class="nav-link" data-scroll-target="#choix-du-modèle-final">Choix du modèle final</a></li>
  </ul></li>
  <li><a href="#diagnostics-des-résidus-sur-le-modèle-final" id="toc-diagnostics-des-résidus-sur-le-modèle-final" class="nav-link" data-scroll-target="#diagnostics-des-résidus-sur-le-modèle-final">Diagnostics des résidus sur le modèle final</a>
  <ul class="collapse">
  <li><a href="#visualisation-des-diagnostics" id="toc-visualisation-des-diagnostics" class="nav-link" data-scroll-target="#visualisation-des-diagnostics">Visualisation des diagnostics</a></li>
  <li><a href="#conclusion-sur-les-corrections" id="toc-conclusion-sur-les-corrections" class="nav-link" data-scroll-target="#conclusion-sur-les-corrections">Conclusion sur les corrections</a></li>
  <li><a href="#analyse-des-points-influents" id="toc-analyse-des-points-influents" class="nav-link" data-scroll-target="#analyse-des-points-influents">Analyse des points influents</a></li>
  </ul></li>
  <li><a href="#conclusion-et-discussion" id="toc-conclusion-et-discussion" class="nav-link" data-scroll-target="#conclusion-et-discussion">Conclusion et discussion</a></li>
  </ul></li>
  <li><a href="#bibliographie" id="toc-bibliographie" class="nav-link" data-scroll-target="#bibliographie">Bibliographie</a></li>
  </ul>
<div class="quarto-other-links"><h2>Other Links</h2><ul><li><a href="https://colin.geind.re/"><i class="bi bi-link-45deg"></i>Colin</a></li><li><a href="https://dataforgood.fr/"><i class="bi bi-link-45deg"></i>Denis</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">La source du bonheur</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>GEINDRE Colin - JAOUEN Denis</strong></p>
<p><a href="https://eco.univ-rennes.fr/master-mathematiques-appliquees-statistique"><strong>Master 1 MAS - Université de Rennes</strong></a> et <a href="https://formations.univ-rennes2.fr/fr/formations/master-37/master-mention-mathematiques-appliquees-statistique-parcours-sciences-des-donnees-intelligence-artificielle-JFTJBMKM.html"><strong>Master 1 MAS - Université Rennes 2</strong></a></p>
<p>La rédaction de ce document s’appuie sur l’utilisation d’IA générative, ainsi que sur des blocs de codes fournit sur des forums comme medium ou stack overflow. Les auteur.ice.s de ces blocs sont remercié.e.s en fin de document.</p>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Sommes-nous heureux ? L’étions-nous plus auparavant ? Quels modèles de société sont les plus heureux ? Et surtout, quelle est la recette du bonheur ? Questions difficiles, mais qui revêtent une importance capitale pour chacun d’entre nous, notamment dans la recherche économique et sociale actuelle.</p>
<p>Le terme de <strong>“Bonheur National Brut”</strong> (ou en anglais “Gross National Happiness”) est apparu pour la première fois au Bhutan, à la fin des années 1970. Jigme Singye Wangchuck, alors roi du pays, déclare “Gross National Happiness is more important than Gross Domestic Product”, une phrase qui a influencé le développement de pays, engageant les politiques nationales et locales autour d’une approche holistique de la notion de progrès, moins centrée sur les marqueurs socio-économiques classiques.</p>
<p>Le <strong>GNHI</strong>, indice de bonheur national développé par le Bhutan, est maintenant utilisé dans de nombreux pays autours du monde. Il est construit sur un ensemble de marqueurs répartis dans 9 pôles considérés comme égaux.</p>
<p>En effet, depuis trop longtemps, l’indice de développement d’un pays a été calculé sur des indices économiques : <strong>PIB</strong>, croissance, taux d’emploi, etc. Ce choix n’est pas neutre, il sert un système particulier qui ne met pas l’humain ou l’environnement au coeur de ses priorités. Cependant, de plus en plus de sociologues et d’économistes préconisent d’ajouter à ces mesures des marqueurs de bien-être sociétal. Mais comment mesurer le bonheur ? Existe-t-il des bases de données sérieuses et fiables permettant de répondre à nos questions ?</p>
<p>Si le <a href="https://ophi.org.uk/gross-national-happiness">GNHI</a> permet un classement selon un index de bonheur, il est déjà construit sur un postulat, celui que le bonheur est expliqué par un ensemble de facteurs socio-économiques définis. Si on veut démontrer ce postulat, on ne peut pas prendre le GNHI comme index de bonheur. Nous avons préféré étudier les résultats du <strong>World Happiness Report</strong> - de <a href="https://www.gallup.com/analytics/318875/global-research.aspx">Gallup</a>, étude annuelle construite sur un questionnaire utilisant des échelles de Cantril (la principale étant “Imaginez une échelle à 10 échelons, l’échelon 0 étant la pire vie que vous pourriez imaginer, le 10 la meilleure. Sur quel échelon êtes-vous actuellement ?”). D’autres études utilisent des échelles similaires, les échelles de Likert. On citera notamment l’Integrated Values Surveys, qui est celle avec la plus longue échelle de temps, mais que nous avons rejeté car le nombre de pays est plus restreint, et la formulation des questions a changé plusieurs fois. Les postulats sont alors plus simples, et on se mettra simplement d’accord sur le fait que :</p>
<ul>
<li><p>La distance mentale entre les différentes réponses au questionnaire est stable, c’est à dire que nous pouvons faire des mathématiques dessus (calculer des moyennes, etc.). Nous supposons une échelle <strong>cardinale</strong> et pas simplement <strong>ordinale</strong>.</p></li>
<li><p>Le bonheur est autodéterminé de manière précise. Nous supposons que l’erreur d’auto-évaluation de son bonheur personnel est une variable aléatoire qui suit une distribution normale. Ainsi, il n’y a pas de biais qui, par exemple, pousserait les personnes malheureuses à s’estimer plus heureuses qu’elles ne le sont.</p></li>
</ul>
<p>Ces hypothèses sont cohérentes avec la littérature scientifique, mais restent fortement débattues. En particulier, l’utilisation d’échelle cardinale plutôt qu’ordinale ne change que très peu les résultats des régressions, comme l’ont démontré plusieurs économistes (Ferris, 2002). Celle-ci est de plus intuitive, et grandement facilitante pour nos calculs. Par contre, il existe un effet plafond/plancher : il est plus difficile de passer de 9 à 10 que de 5 à 6 ; l’échelle n’est probablement pas cardinale dans les extrêmes. Nous faisons là une approximation consciente. La deuxième hypothèse, elle, est corroborée par la loi des <strong>grands nombres</strong> (les données de Gallup sont les plus fournies au monde), et par les différentes études sur les marqueurs de bonheur (taux de suicide, expressions faciales…), qui tendent à démontrer que les sujets ne mentent pas sur leur bonheur. Mais certaines cultures valorisent (latino-américaines) ou dévalorisent (Japon, Corée) socialement de se dire heureux, ce qui peut tirer les résultats vers le haut ou vers le bas. De plus, le tapis roulant hédonique, ou l’adaptation à ses conditions, ainsi que la désirabilité sociale qui pousse les répondants à paraître normaux aux yeux des enquêteurs, peuvent créer une homogénisation des résultats.</p>
<p>Pour contrer ces biais, on introduit parfois des <strong>effets fixes “pays”</strong>, comme les membres de l’OCDE, les pays Latino-américains, etc.</p>
<p>Un dernier problème que nous voulons aborder est celui de la barrière de la langue. Est-ce que tout le monde à la même perception du “bonheur”, ou est-ce que les mots, le langage utilisé pour définir cette notion change au point que la langue influence les réponses ? Mais de nombreuses études ont montré que l’on arrivait relativement bien à apprécier le bonheur des autres, quelque soit notre pays d’origine et celui de l’autre, impliquant que le bonheur revêt une définition globale relativement comprise partout (voir Sandvil, 1993 et Diner &amp; Lucas, 1999).</p>
<p>Nous nous attendons à voir une <strong>corrélation</strong> entre l’indice de bonheur du WHR, et différents indicateurs socio-économiques. De plus, nous nous attendons a voir les biais culturels sus-cités.</p>
</section>
<section id="plan" class="level1">
<h1>Plan</h1>
<ul>
<li>Introduction</li>
<li>Cadre méthodologique
<ul>
<li>Modèle de régression</li>
<li>Corrections et transformations de variables</li>
</ul></li>
<li>Analyse des données
<ul>
<li>Cadre des données</li>
<li>Pré-traitement des données
<ul>
<li>Données manquantes</li>
<li>Suppression des doublons</li>
<li>Recherche des outliers</li>
<li>Transformation des données</li>
</ul></li>
<li>Analyses descriptives univariées
<ul>
<li>Variables explicatives</li>
<li>Variable cible</li>
</ul></li>
<li>Analyses descriptives multivariées
<ul>
<li>Corrélations entre variables</li>
<li>Analyse des interactions</li>
</ul></li>
</ul></li>
<li>Résultats et discussion
<ul>
<li>Modélisation principale</li>
<li>Modélisation avancée et sélection de variables</li>
<li>Diagnostics des résidus sur le modèle final</li>
<li>Analyse des points influents</li>
<li>Conclusion sur les corrections</li>
</ul></li>
<li>Conclusion</li>
<li>Bibliographie</li>
</ul>
</section>
<section id="cadre-méthodologique" class="level1">
<h1>Cadre méthodologique</h1>
<p>Le cadre méthodologique général est celui de la régression linéaire, avec une estimation des moindres carrés ordinaires. En fonction des données, des corrections éventuelles (white, MCG, etc.) pourront être envisagées. Pour chaque partie, une méthodologie plus précise sera discutée.</p>
<section id="modèle-de-régression" class="level2">
<h2 class="anchored" data-anchor-id="modèle-de-régression">Modèle de régression</h2>
<p>Voici la formulation mathématique du modèle linéaire estimé par moindres carrés ordinaires (MCO), en notation matricielle. <span class="math display">\[
y = X\beta + \varepsilon
\]</span></p>
<p>Dans notre cas, le modèle est formulé ainsi :</p>
<p><span class="math display">\[
\begin{align}
  Happiness &amp;= \beta_0\\
  &amp;+ \beta_1 Political\_Corruption + \beta_2 GDP\_per\_capita + \beta_3 Lifespan\\
  &amp;+ \beta_4 Net\_Migration + \beta_5 Overweight\_Adults + \beta_6 Population\_density \\
  &amp;+ \beta_7 KWH\_pp\_pc + \beta_8 Military\_Expenses + \beta_9 Population\_Growth \\
  &amp;+ \beta_{10} Primary\_School\_Enrollment + \beta_{11} OCDE\\
  &amp;+ \varepsilon
\end{align}
\]</span></p>
<p>On estime alors les paramètres via la méthode des moindres carrés ordinaires : <span class="math display">\[
\hat{\beta}_{MCO} = \operatorname*{arg\,min}\beta \sum{\varepsilon_i^2} = (X'X)^{-1}X'y
\]</span></p>
<p>Cette méthode assume certaines hypothèses :</p>
<ul>
<li><p><strong>Linéarité</strong> : la relation entre les variables explicatives et la variable cible est linéaire (et la variable cible est continue).</p></li>
<li><p><strong>Exogénéité</strong> : les variables explicatives ne sont pas corrélées avec le terme d’erreur, <span class="math inline">\(E(X'\varepsilon) = 0\)</span>.</p></li>
<li><p><strong>Homoscédasticité</strong> : la variance des erreurs est constante, <span class="math inline">\(\operatorname{Var}(\varepsilon) = \sigma^2 I\)</span>.</p></li>
<li><p><strong>Normalité</strong> : les résidus sont distribuées normalement, <span class="math inline">\(\varepsilon \sim \mathcal{N}(0, \sigma^2)\)</span>.</p></li>
<li><p><strong>Absence d’autocorrélation des variables explicatives</strong> : les variables explicatives ne sont pas corrélées entre elles.</p></li>
<li><p><strong>Absence d’autocorrélation des résidus</strong>, <span class="math inline">\(\operatorname{Cov}(\varepsilon_i, \varepsilon_j) = 0\)</span> pour <span class="math inline">\(i \neq j\)</span>.</p></li>
</ul>
<p>Sous homoscédasticité : <span class="math inline">\(\operatorname{Var}(\hat{\beta}_{MCO}) = \sigma^2 (X'X)^{-1}\)</span></p>
<p>En présence d’hétéroscédasticité, la variance générale s’écrit avec la matrice diagonale <span class="math inline">\(\Omega\)</span>, <span class="math inline">\((Var(\varepsilon)=\Omega)\)</span> : <span class="math inline">\(\operatorname{Var}(\hat{\beta}_{MCO}) = (X'X)^{-1} X' \Omega X (X'X)^{-1}\)</span></p>
</section>
<section id="corrections-et-transformations-de-variables" class="level2">
<h2 class="anchored" data-anchor-id="corrections-et-transformations-de-variables">Corrections et transformations de variables</h2>
<p>On peut opérer des transformations de varibales pour que notre modèle soit plus explicatif ou plus robuste. En voici quelques exemples ainisi que leurs modèles correspondants :</p>
<ul>
<li>Modèle niveau - niveau : <span class="math inline">\(y_i = \alpha + \beta x_i + u_i\)</span>. Ici, β donne un effet absolu de x sur y.</li>
<li>Modèle Log‑niveau : <span class="math inline">\(y_i = \alpha + \beta \log(x_i) + u_i\)</span>. Ici, β est la variation absolue de y pour une variation proportionnelle de x (approx. effet semi‑élasticité).</li>
<li>Modèle Log‑log : <span class="math inline">\(\log(y_i) = \alpha + \beta \log(x_i) + u_i\)</span>. Ici, β représente l’élasticité, lepourcentage de y lorsque x varie de 1%.</li>
<li>Modèle quadratique : <span class="math inline">\(y_i = \alpha + \beta_1 x_i + \beta_2 x_i^2 + u_i\)</span>. Permet de capturer des capturer des effets non‑linéaires comme les effets convexe ou concave.</li>
<li>Modèle avec interaction : <span class="math inline">\(y_i = \alpha + \beta_1 x_i + \beta_2 D_i + \beta_3 (x_i \times D_i) + u_i\)</span>. Donne un effet de x différent selon la modalité D. On étudie les effets croisés de la même façon.</li>
</ul>
</section>
</section>
<section id="analyse-des-données" class="level1">
<h1>Analyse des données</h1>
<section id="cadre-des-données" class="level2">
<h2 class="anchored" data-anchor-id="cadre-des-données">Cadre des données</h2>
<p>Nous avons tenté d’avoir le cadre le plus global possible. Ainsi nous tendons d’étudier les 147 pays référencés par le world happiness report. Après sélection de nos variables et traitement des données, il nous reste 125 pays à étudier.</p>
<center>
<div id="tab1" class="fig">
<p>Tableau 1 : Variables étudiées</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Code de la série</th>
<th>Définition</th>
<th style="text-align: center;">Unité</th>
<th style="text-align: right;">Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Code</td>
<td>Le code du pays</td>
<td style="text-align: center;">Caractères</td>
<td style="text-align: right;">-</td>
</tr>
<tr class="even">
<td style="text-align: left;">S</td>
<td>La moyenne de 2013 à 2023 d’un index de corruption politique allant de 0 à 1</td>
<td style="text-align: center;">Index allant de 0 à 1</td>
<td style="text-align: right;"><a href="https://data360.worldbank.org/en/indicator/">World Bank</a></td>
</tr>
<tr class="odd">
<td style="text-align: left;">GDP_per_capita</td>
<td>La moyenne de 2013 à 2023 du PIB par habitant</td>
<td style="text-align: center;">En dollar américain par habitant</td>
<td style="text-align: right;"><a href="https://data360.worldbank.org/en/indicator/WB_WDI_NY_GDP_PCAP_CD">World Bank</a></td>
</tr>
<tr class="even">
<td style="text-align: left;">Lifespan</td>
<td>La moyenne de 2013 à 202O de l’espérance de vie à la naissance</td>
<td style="text-align: center;">En années</td>
<td style="text-align: right;"><a href="https://data360.worldbank.org/en/indicator/WB_ESG_SP_DYN_LE00_IN">World Bank</a></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Net_Migration</td>
<td>La moyenne de 2013 à 2020 de la migration nette</td>
<td style="text-align: center;">En nombre de personnes</td>
<td style="text-align: right;"><a href="https://data360.worldbank.org/en/indicator/WB_WDI_SM_POP_NETM">World Bank</a></td>
</tr>
<tr class="even">
<td style="text-align: left;">Overweight_Adults</td>
<td>La moyenne de 2013 à 2016 de la proportion d’adulte de 18 ans et plus dont l’IMC est supérieur à 25.</td>
<td style="text-align: center;">En pourcentage</td>
<td style="text-align: right;"><a href="https://data360.worldbank.org/en/indicator/WB_HNP_SH_STA_OWAD_ZS">World Bank</a></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Population_density</td>
<td>La moyenne de 2013 à 2021 de la densité de population en nombre d’habitant à la mi-année par kilomètres carrés</td>
<td style="text-align: center;">En habitant par kilomètre carré</td>
<td style="text-align: right;"><a href="https://data360.worldbank.org/en/indicator/WB_WDI_EN_POP_DNST">World Bank</a></td>
</tr>
<tr class="even">
<td style="text-align: left;">KWH_pp_pc</td>
<td>La moyenne de 2013 à 2023 de la consommation en kilowattheure par personne</td>
<td style="text-align: center;">En kilowattheure par personne</td>
<td style="text-align: right;"><a href="https://ourworldindata.org/grapher/per-capita-energy-use?overlay=download-data">World Bank</a></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Military_Expenses</td>
<td>La moyenne de 2013 à 2023 du pourcentage du PIB dédié à la dépense militaire</td>
<td style="text-align: center;">En pourcentage du PIB</td>
<td style="text-align: right;"><a href="https://ourworldindata.org/grapher/military-spending-as-a-share-of-gdp-sipri?overlay=download-data">Our World in Data</a></td>
</tr>
<tr class="even">
<td style="text-align: left;">Population_Growth</td>
<td>La moyenne de 2013 à 2023 de la croissance en pourcentage de la population</td>
<td style="text-align: center;">En pourcentage</td>
<td style="text-align: right;"><a href="https://ourworldindata.org/grapher/population-growth-rates?tab=map&amp;overlay=download-data">Our World in Data</a></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Primary_School_Enrollment</td>
<td>La moyenne de 2013 à 2022 du nombre d’étudiant inscrits en école primaire divisé par la population du groupe d’age multiplié par 100</td>
<td style="text-align: center;">En pourcentage</td>
<td style="text-align: right;"><a href="https://data360.worldbank.org/en/indicator/WB_ESG_SE_PRM_ENRR">World Bank</a></td>
</tr>
<tr class="even">
<td style="text-align: left;">OCDE</td>
<td>Une indicatrice avec 1 si le pays est membre de l’OCDE et 0 sinon</td>
<td style="text-align: center;">Indicatrice</td>
<td style="text-align: right;"><a href="https://www.oecd.org/en/about/members-partners.html">OCDE</a></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Happiness</td>
<td>La moyenne de 2013 à 2023 de l’indice du bonheur calculé par le World Happiness Index</td>
<td style="text-align: center;">Index allant de 0 à 10</td>
<td style="text-align: right;"><a href="https://www.worldhappiness.report/data-sharing/">World Happiness Report</a></td>
</tr>
</tbody>
</table>
</div>
</center>
</section>
<section id="prétraitement-et-nettoyage-des-données" class="level2">
<h2 class="anchored" data-anchor-id="prétraitement-et-nettoyage-des-données">Prétraitement et nettoyage des données</h2>
<p>Ayant des données allant de 1789 à 2024, nous avons effectué des <strong>moyennes</strong> depuis 2013 et jusqu’à un maximum de 2023 sur toutes les données étudiées.</p>
<p>Cette approche nous donne deux avantages. Le premier est de récolter un maximum d’individus malgré un grand nombre de données manquantes. Le second est d’atténuer les tendances qui on pu se passer dans des temps plus courts sur cette décennie, limitant les individus aberrants dans nos données.</p>
<p>Intéressons nous brièvement aux 26 pays exclus par notre sélection de jeux de données :</p>
<center>
<hr>
<div id="tab2" class="fig">
<p>Tableau 2 : Pays exclus par notre sélection de données</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
================================
         Pays_perdus        OCDE
--------------------------------
1          Bolivia           0  
2          Comoros           0  
3           Congo            0  
4         Costa Rica         1  
5       Côte d’Ivoire        0  
6          DR Congo          0  
7           Egypt            0  
8           Gambia           0  
9   Hong Kong SAR of China   0  
10         Iceland           1  
11           Iran            0  
12           Iraq            0  
13          Kosovo           0  
14        Kyrgyzstan         0  
15         Lebanon           0  
16          Libya            0  
17          Panama           0  
18    Republic of Korea      0  
19   Republic of Moldova     0  
20       Saudi Arabia        0  
21         Slovakia          0  
22    State of Palestine     0  
23 Taiwan Province of China  0  
24         Türkiye           1  
25        Venezuela          0  
26          Yemen            0  
--------------------------------</code></pre>
</div>
</div>
</div>
<hr>
</center>
<p>On voit premièrement la présence de territoires dont l’existence administrative ou l’indépendance est contestée avec Hong Kong, Taiwan, le Kosovo et la Palestine.</p>
<p>Parmi les 22 autres pays, on voit qu’on n’a pas exclusivement des pays pauvres, petits ou peu influents. Cependant, en observant la variable OCDE, on s’aperçoit qu’il n’y a que 13,6% de ces pays qui sont membres de l’OCDE alors que dans nos données restantes, 34,4% des pays sont membres.</p>
<p>On reconnait donc qu’on perd majoritairement des pays en développement et des pays du Sud global. Cela dit, rien ici ne nous permet, à première vue, de penser que ces pays affecteraient significativement notre modèle. On accepte de donc de tirer des conclusions générales malgré leur absence.</p>
</section>
<section id="analyse-descriptive-univariée-des-données" class="level2">
<h2 class="anchored" data-anchor-id="analyse-descriptive-univariée-des-données">Analyse descriptive univariée des données</h2>
<p>Voyons maintenant de plus près les données restantes que nous allons utiliser.</p>
<hr>
<center>
<div id="tab3" class="fig">
<p>Tableau 3 : Statistiques descriptives des variables étudiées</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
===================================================================================
Statistic                   Mean     St. Dev.       Min       Median       Max     
-----------------------------------------------------------------------------------
Political_Corruption        0.47       0.30        0.002       0.50        0.95    
GDP_per_Capita            16,670.31 22,709.09     230.93     6,175.42   118,437.30 
Lifespan                    72.09      8.39        52.10       74.11      83.99    
Net_Migration             8,166.03  201,494.10 -1,632,118.00   85.12   1,206,926.00
Overweight_Adults           45.86     16.31        17.38       54.40      72.78    
Population_Density         211.95     729.00       1.99        80.05     7,814.10  
KWH_pp_pc                 25,913.75 35,190.72     224.22     15,016.75  213,333.10 
Military_Expenses           1.89       1.46        0.16        1.46        8.53    
Population_Growth           1.28       1.22        -1.91       1.14        3.93    
Primary_School_Enrollment  101.71     13.83        8.45       100.72      138.91   
Happiness                   5.46       1.12        2.86        5.48        7.67    
-----------------------------------------------------------------------------------</code></pre>
</div>
</div>
</div>
<hr>
</center>
<p>On voit tout de suite, par comparaison de la moyenne et de la médiane de chaque variable, certaines tendances : le PIB par habitant contient des individus qui tirent la moyenne vers le haut, idem pour la migration, le KWH par habitant et la densité de population.</p>
<p>En étudiant les minimums, maximums, et écarts-type de ces quatre variables, on remarque qu’il ne s’agit probablement que de quelques individus dont les valeurs très fortes déforment les moyennes. Par exemple, la densité de population a une étendue de 7812, une médiane de 80 et un écart -type de seulement 65. On s’attend à observer dans ces variables des <strong>petits groupes d’individus</strong> aux valeurs très élevées.</p>
<p>Un effet inverse et de moindre importance peut aussi être constaté quand au surpoids des adultes. On voit que la moyenne est légèrement tirée en dessous de la médiane.</p>
<p>Les dépenses militaires ayant une moyenne légèrement plus élevée que la médiane et un écart-type faible malgré un maximum assez élevé, on s’attend à observer très peu d’individus avec des valeurs très élevées mais une concentration importante des individus autour de la médiane.</p>
<p>Le reste des variables ont l’air d’être peu dispersées. On peut s’atttendre à y voir une répartition normale des valeurs.</p>
<p>À présent, intéressons nous à la variable que l’on cherche à expliquer :</p>
<div id="fig1" class="fig">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="rendu_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>Figure 1 : Histogramme du score de bonheur</p>
</div>
<div id="fig2" class="fig">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="rendu_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>Figure 2 : Boxplot du score de bonheur</p>
</div>
<p>A première vue, la fig.1 semble difficilement suivre une loi normale. On repère cela à une certaine symétrie et une concentration d’indivus autour du centre, particulièrement deux pics : l’un proche de 4,5 et le second de 6.</p>
<p>La fig.2 présente une répartition très équilibrée de notre variable explicative. On n’y repère pas de tendances particulières si ce n’est que les deux quarts les moins heureux sont légèrement plus grands. On dénote l’absence d’individus aberrants : les valeurs sont toutes réparties de manière équilibrée.</p>
<section id="analyse-de-chaque-variable-explicative" class="level3">
<h3 class="anchored" data-anchor-id="analyse-de-chaque-variable-explicative">Analyse de chaque variable explicative</h3>
<div id="fig3" class="fig">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="rendu_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Figure 3 : Histogrammes des variables ayant une distribution proche de la normale</p>
</div>
<p>Au vu de la symétrie de leurs histogrammes on peut considérer que la croissance de la population, l’inscription à l’école primaire, les dépenses militaires et la migration peuvent être proches de lois normales.</p>
<div id="fig4" class="fig">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="rendu_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Figure 4 : Histogrammes des variables ayant une distribution décroissante</p>
</div>
<p>La consommation d’énergie, la densité de population et le PIB par habitant semblent suivre des lois inverses avec une importante concentration des individus dans les valeurs basses et de moins en moins d’individus ayant des valeurs élevées.</p>
<p>Dans l’histogramme de la densité de population (6), il y a un seul individu, à près de 8000 habitants par km carré : Singapour. On le retire un instant pour “zoomer” sur la fréquence des individus dans les valeurs les plus faibles (cf.&nbsp;6b). On y voit que la répartition ne suit pas tout à fait une loi inverse puisque le pic de population n’est pas au début. On ne peut pas pour autant associer la densité de population à une loi normale, plutôt à une loi du Chi-deux.</p>
<div id="fig5" class="fig">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="rendu_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Figure 5 : Histogrammes des variables ayant une distribution peu claire</p>
</div>
<p>Ces derniers histogrammes ne nous sont pas d’une grande utilité si ce n’est pour dire que la corruption politique, le surpoids et l’espérance de vie ne semblent pas suivre des lois classiques. Les nuages de point et les boxplots nous seront peut-être plus utiles pour analyser ces variables.</p>
<p>Cela dit, on visualise deux pics de surreprésentation (autour de 25 et 55) dans l’histogramme du surpoids (10) et une certaine absence des individus dans les valeurs moyennes (entre 30 et 50). On peut également voir une concentration des espérances de vie au delà de 70 ans (9).</p>
<div id="fig11" class="fig">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="rendu_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Figure 6 : Boxplots des variables explicatives</p>
</div>
<p>On peut comparer ici une distribution équilibrée et espacée, celle de la corruption politique, avec des distributions très concentrées pour les boxplots 3 à 6 et une distribution inégale pour ce qui est du PIB par habitant.</p>
<p>Comme sur les graphes précédents (fig 3 et 4), on remarque une importante concentration des individus pour ce qui est de la migration, la densité de population et les inscriptions à l’école primaire. On visualise bien la concentration des pays les plus pauvres dans la moitié basse de boxplot du PIB par habitant qui nous a poussé à tester une transformation logarithmique.</p>
<p>Un affichage en boîte à moustache permet de repérer très facilement les <strong>outliers</strong>, les individus les plus aberrants qui referont surface dans les graphiques suivants :</p>
<ul>
<li><p>On repère dans le boxplot de l’inscription à l’école primaire (fig 6 - Boxplot n°5) un individu atypique proche de 0, il s’agit de la <strong>Somalie</strong> avec moins de 9% d’inscrits.</p></li>
<li><p>De la même manière dans le boxplot de la densité de population (fig 6 - Boxplot n°4), on repère à nouveau <strong>Singapour</strong> avec une densité titanesque de près de 8000 habitants au km2.</p></li>
<li><p>Dans le boxplot de la migration (fig 6 - Boxplot n°3),, le <strong>Pakistan</strong> apparait tout en bas avec plus d’1,5 million de migration nettte négative et les <strong>Etats-Unis</strong> tout en haut avec plus d’1,2 million de migration nette positive.</p></li>
<li><p>Le <strong>Luxembourg</strong> est l’individu avec le PIB le plus élevé (fig 6 - Boxplot n°2).</p></li>
<li><p>Et le <strong>Qatar</strong> est l’individu tout à droite dans l’histogramme de la consommation énergétique (fig 4 - histogramme n° 7).</p></li>
</ul>
</section>
</section>
<section id="analyse-descriptive-bivariée-des-données" class="level2">
<h2 class="anchored" data-anchor-id="analyse-descriptive-bivariée-des-données">Analyse descriptive bivariée des données</h2>
<div id="fig6" class="fig">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="rendu_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Figure 7 : Corrélations des variables explicatives avec l’indice de bonheur</p>
</div>
<p>On remarque ici les variables les plus et les moins corrélées à l’indice du bonheur. L’espérance de vie, le PIB/hab, le surpoids et la consommation énergétique sont très corrélés positivement avec l’indice de bonheur tandis que la corruption politique et la croissance de population semblent elles être corrélées négativement.<br>
Les autres variables sont peu ou très peu corrélées à l’indice de bonheur.</p>
<p>On va voir par la suite que ces corrélations se traduisent en relations linéaires avec des droites décroissantes pour les variables corrélées négativement et inversement. On verra aussi que les variables avec les plus petites corrélations ont les coefficients directeurs les plus faibles et inversement.</p>
<div id="fig7" class="fig">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="rendu_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Figure 8 : Nuage de points entre l’espérance de vie et l’indice de bonheur</p>
</div>
<p>Premièrement, on remarque une bonne linéarité positive entre l’indice de bonheur et l’espérance de vie à la naissance, les points semblent bien décrire une droite. C’est notre variable la plus corrélée à l’indice de bonheur et, sans surprise, la mieux représentée linéairement.</p>
<div id="fig8" class="fig">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="rendu_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Figure 9 : Nuages de points assez dispersés</p>
</div>
<p>Ensuite, nous avons trois variables qui ont une relation linéaire avec l’indice de bonheur mais dont les nuages de points sont très dispersés : la corruption politique, la croissance de population et le surpoids.</p>
<p>On remarque dans le nuage de point de la corruption politique un ensemble d’individus très proches, des pays heureux et peu corrompus qui ensemble ont un effet important sur la droite de linéarité et qui lui donne son aspect décroissant.</p>
<p>On remarque également les deux concentrations d’individus dans le graphe du surpoids, comme on pouvait l’apercevoir dans l’histogramme du surpoids (fig.&nbsp;5).</p>
<p>Notre quatrième graphe représente les dépenses militaires : la variable la moins corrélée à l’indice de bonheur (fig.&nbsp;6). Sans surprise, on ne voit pas de linéarité avec l’indice de bonheur, la droite est horizontale et le nuage de point est très dispersé bien qu’on aperçoive les quelques individus dont le budget alloué aux dépenses militaires est plus élevé.</p>
<div id="fig9" class="fig">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="rendu_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Figure 10 : Nuages de points les plus concentrés avec et sans leurs individus les plus aberrants</p>
</div>
<p>Voyons maintenant les variables dont les individus sont très concentrés, mettant en évidence certains individus aberrants repérés plus tôt (figure 3 et 4) : les USA et le Pakistan pour la migration, Singapour pour la densité de population et la Somalie pour le taux d’inscription à l’école primaire.</p>
<p>Cela dit, ces individus ne sont pas mal projetés vis-à-vis des droites de relation linéaire avec l’indice de bonheur. Ils ne semblent pas avoir d’effet important sur leurs droites respectives. Seuls le Pakistan et la Somalie aplatissent légèrement leurs droites.</p>
<p>Leur unicité à cependant un effet très important sur leurs intervalles de confiance respectifs (indiqués en bleu clair. Le manque d’individu dans les extrémités des graphes créé un intervalle de confiance très large, ne nous permettant qu’une faible prévision quant à la relation entre la variable concernée et l’indice de bonheur.</p>
<p>Afin d’observer les nuages de points concentrés de plus près, nous avons retiré les individus aberrants susnommés dans les graphes aux points bleus. Comme on peut le voir, cela ne permet pas d’obtenir une linéarité claire de la relation entre l’indice de bonheur et les variables étudiées. Tout comme les dépenses militaires, ces variables ne semblent pas ou peu corrélées à notre score de bonheur et leur forte concentration d’individus complique toute étude visuelle du lien avec le bonheur.</p>
<div id="fig10" class="fig">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="rendu_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Figure 11 : Nuages de points avec l’indice de bonheur des variables bénéficiant d’une transformation logarithmique et lesdites transformations</p>
</div>
<p>Enfin, nous nous intéressons à des transformations de variables dont les graphes initiaux ne donnaient pas une belle linéarité avec l’indice de bonheur. Le PIB/hab et la consommation énergétique ont une forte concentration des individus autour des valeurs faibles et quelques individus aux valeurs élevées décrivant originellement une relation plus logarithmique que linéaire.</p>
<p>Appliquer un logarithme au PIB par habitant et à la consommation énergétique permet un lien linéaire très clair avec l’indice de bonheur. La transformation resserre également l’intervalle de confiance, nous assurant d’une bonne relation linéaire. Cette réalisation nous indique que nous obtiendrons de meilleurs modèles en utilisant ces transformations logarithmiques plutôt que les variables originelles.</p>
<div id="fig12" class="fig">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="rendu_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Figure 12 : Boxplot du bonheur en fonction de l’appartenance à l’OCDE</p>
</div>
<p>Le pays membre le moins heureux étant plus heureux que la majorité de pays non-membres, il est clair que les pays membres de l’OCDE ont un bonheur bien plus élevé que les non-membres. On s’attend donc à observer une certaine significativité de l’OCDE dans notre modèle.</p>
</section>
</section>
<section id="analyse-et-discussion-des-résultats" class="level1">
<h1><strong>Analyse et discussion des résultats</strong></h1>
<section id="modélisation-principale" class="level2">
<h2 class="anchored" data-anchor-id="modélisation-principale">Modélisation principale</h2>
<p>Nous allons commencer par comparer deux modèles. Le premier, que l’on appellera <strong>reglin</strong>, correspond à la régression linéaire complète, sans transformation de variable, et le deuxième <strong>reglog</strong>, à une régression avec une transformation par logarithme sur les variables modifiées en figure 11.</p>
<hr>
<center>
<div id="tab4" class="fig">
<p>Tableau 4 : Résumés de reglin et reglog</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
==================================================================
                                       Dependent variable:        
                               -----------------------------------
                                            Happiness             
                                      (1)               (2)       
------------------------------------------------------------------
Political_Corruption              0.32 (0.26)      0.51** (0.26)  
KWH_pp_pc                       0.0000 (0.0000)                   
GDP_per_Capita                 0.0000*** (0.0000)                 
log(KWH_pp_pc)                                      0.06 (0.10)   
log(GDP_per_Capita)                                0.38*** (0.12) 
Lifespan                         0.06*** (0.01)    0.04*** (0.01) 
Net_Migration                   -0.0000 (0.0000)  -0.0000 (0.0000)
Overweight_Adults               0.02*** (0.005)    0.01* (0.005)  
Population_Density              -0.0000 (0.0001)  0.0000 (0.0001) 
Military_Expenses                -0.09** (0.04)    -0.09** (0.04) 
Population_Growth                 0.04 (0.05)      0.13*** (0.05) 
OCDE1                            0.40** (0.17)     0.44*** (0.16) 
Primary_School_Enrollment       -0.01** (0.003)    -0.01* (0.003) 
Constant                          0.76 (0.85)      -1.41* (0.80)  
------------------------------------------------------------------
Observations                          125               125       
R2                                    0.81              0.83      
Adjusted R2                           0.79              0.81      
Residual Std. Error (df = 113)        0.51              0.49      
F Statistic (df = 11; 113)          44.23***          49.40***    
==================================================================
Note:                                  *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
</div>
</center>
<hr>
<p>Nos deux modèles expliquent plus de 80% de la variance de l’indice de bonheur. Cependant, le modèle avec transformation logarithmique (reglog) a un R² ajusté légèrement supérieur, ce qui indique une meilleure capacité explicative.</p>
<p>Nos variables significatives, par ordre de significativité, sont l’espérance de vie, le surpoids, le PIB par habitant, la dépense militaire, la participation à l’OCDE et l’inscription à l’école primaire.</p>
</section>
<section id="modélisation-avancée-et-sélection-de-variables" class="level2">
<h2 class="anchored" data-anchor-id="modélisation-avancée-et-sélection-de-variables">Modélisation avancée et sélection de variables</h2>
<p>Nous partons du modèle logarithmique <code>reglog</code> qui semble le plus performant de par son meilleur R² ajusté.</p>
<section id="traitement-de-la-multicolinéarité" class="level3">
<h3 class="anchored" data-anchor-id="traitement-de-la-multicolinéarité">Traitement de la multicolinéarité</h3>
<p>Examinons les facteurs d’inflation de la variance (VIF) pour détecter une potentielle multicolinéarité entre les variables.</p>
<hr>
<center>
<div id="tab5" class="fig">
<p>Tableau 5 : VIF des variables du modèle complet (reglog)</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
===============================
Variable                   VIF 
-------------------------------
Political_Corruption      3.12 
log(KWH_pp_pc)            13.01
log(GDP_per_Capita)       16.82
Lifespan                  5.24 
Net_Migration             1.20 
Overweight_Adults         3.39 
Population_Density        1.30 
Military_Expenses         1.38 
Population_Growth         1.59 
OCDE                      2.63 
Primary_School_Enrollment 1.05 
-------------------------------</code></pre>
</div>
</div>
</div>
</center>
<hr>
<p><strong>Analyse de la multicolinéarité :</strong> Les résultats indiquent une multicolinéarité sévère pour le PIB par habitant (<strong>16.82</strong>) et la consommation d’énergie (<strong>13.01</strong>), ainsi qu’une valeur limite pour l’espérance de vie (<strong>5.24</strong>). Bien que le PIB présente le VIF le plus élevé, il constitue la variable économique de référence. La consommation d’énergie (<code>KWH_pp_pc</code>) étant une proxy de l’industrialisation très corrélée au PIB, sa suppression est la correction logique pour réduire la redondance sans perdre l’information sur la richesse. Nous retirons donc <code>KWH_pp_pc</code>.</p>
<hr>
<center>
<div id="tab6" class="fig">
<p>Tableau 6 : VIF des variables de reglog après suppression de la consommation d’énergie</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
==============================
Variable                  VIF 
------------------------------
Political_Corruption      3.06
log(GDP_per_Capita)       7.50
Lifespan                  5.06
Net_Migration             1.20
Overweight_Adults         3.29
Population_Density        1.29
Military_Expenses         1.20
Population_Growth         1.50
OCDE                      2.43
Primary_School_Enrollment 1.05
------------------------------</code></pre>
</div>
</div>
</div>
</center>
<hr>
<p>L’espérance de vie conserve un VIF problématique (&gt;5) après cette suppression, elle pourrait également être écartée par la sélection automatique ci-après, mais nous choisissons de la conserver pour l’instant car elle représente la dimension “Santé” distincte de la “Richesse”.</p>
</section>
<section id="sélection-de-variables-stepwise-par-aic" class="level3">
<h3 class="anchored" data-anchor-id="sélection-de-variables-stepwise-par-aic">Sélection de variables (Stepwise par AIC)</h3>
<p>Nous utilisons une procédure de sélection pas à pas descendante (backward) basée sur le critère d’information d’Akaike (AIC) pour ne garder que les variables pertinentes.</p>
<hr>
<center>
<div id="tab7" class="fig">
<p>Tableau 7 : Résumé du modèle optimisé par AIC</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
=====================================================
                              Dependent variable:    
                          ---------------------------
                                   Happiness         
-----------------------------------------------------
Political_Corruption            0.545** (0.248)      
log(GDP_per_Capita)            0.438*** (0.076)      
Lifespan                       0.042*** (0.011)      
Overweight_Adults               0.008* (0.004)       
Military_Expenses              -0.081** (0.033)      
Population_Growth              0.118*** (0.043)      
OCDE1                          0.396*** (0.148)      
Primary_School_Enrollment      -0.007** (0.003)      
Constant                        -1.484* (0.766)      
-----------------------------------------------------
Observations                          125            
R2                                   0.827           
Adjusted R2                          0.815           
Residual Std. Error            0.484 (df = 116)      
F Statistic                 69.122*** (df = 8; 116)  
=====================================================
Note:                     *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
</div>
</center>
<hr>
<p>Ce modèle ne contient plus que les variables qui apportent une information significative au sens de l’AIC. C’est notre nouveau modèle de référence.</p>
<p>On constate l’absence de variables précédemment non significatives : la dépense militaire et la densité de population.</p>
</section>
<section id="test-de-non-linéarités-et-dinteractions" class="level3">
<h3 class="anchored" data-anchor-id="test-de-non-linéarités-et-dinteractions">Test de non-linéarités et d’interactions</h3>
<p>Il est fréquent en économie du bonheur d’observer des rendements décroissants (déjà capturé par le logarithme du PIB). Nous pouvons aussi tester si l’effet de la richesse dépend du niveau de développement avec l’interaction OCDE x PIB.</p>
<p>Testons un modèle avec cette interaction :</p>
<hr>
<center>
<div id="tab8" class="fig">
<p>Tableau 8 : Résumés du modèle final et du modèle avec interaction</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
=========================================================================
                                        Dependent variable:              
                          -----------------------------------------------
                                             Happiness                   
                                    (1)                     (2)          
-------------------------------------------------------------------------
Political_Corruption          0.545** (0.248)         0.560** (0.247)    
log(GDP_per_Capita)          0.438*** (0.076)        0.400*** (0.080)    
Lifespan                     0.042*** (0.011)        0.043*** (0.011)    
Overweight_Adults             0.008* (0.004)          0.010** (0.005)    
Military_Expenses            -0.081** (0.033)        -0.076** (0.033)    
Population_Growth            0.118*** (0.043)         0.106** (0.044)    
OCDE1                        0.396*** (0.148)         -1.835 (1.537)     
Primary_School_Enrollment    -0.007** (0.003)         -0.006* (0.003)    
log(GDP_per_Capita):OCDE1                              0.219 (0.150)     
Constant                      -1.484* (0.766)         -1.298* (0.772)    
-------------------------------------------------------------------------
Observations                        125                     125          
R2                                 0.827                   0.830         
Adjusted R2                        0.815                   0.816         
Residual Std. Error          0.484 (df = 116)        0.482 (df = 115)    
F Statistic               69.122*** (df = 8; 116) 62.275*** (df = 9; 115)
=========================================================================
Note:                                         *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
</div>
</center>
<hr>
<center>
<div id="tab9" class="fig">
<p>Tableau 9 : Test d’anova entre le modèle final et celui avec interaction</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Modèle Final: 
Happiness ~ Political_Corruption + log(GDP_per_Capita) + Lifespan + Overweight_Adults 
+ Military_Expenses + Population_Growth + OCDE + Primary_School_Enrollment</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Modèle avec Interaction : 
Happiness ~ Political_Corruption + log(GDP_per_Capita) + Lifespan + Overweight_Adults
+ Military_Expenses + Population_Growth + OCDE + Primary_School_Enrollment 
+ log(GDP_per_Capita)*OCDE</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
==========================================
  Res.Df  RSS   Df Sum of Sq   F   Pr(&gt; F)
------------------------------------------
1  116   27.164                           
2  115   26.670 1    0.493   2.127  0.147 
------------------------------------------</code></pre>
</div>
</div>
</div>
</center>
<hr>
<p><strong>Analyse de l’interaction :</strong> Le test ANOVA compare le modèle avec et sans l’interaction <code>OCDE * GDP</code>. La p-value obtenue (<strong>0.147</strong>) est supérieure au seuil standard de 0.05. Cela signifie que l’ajout du terme d’interaction n’améliore pas significativement la qualité du modèle. L’hypothèse selon laquelle l’importance du PIB sur le bonheur différerait significativement entre les pays de l’OCDE et les autres n’est pas validée statistiquement par nos données.</p>
</section>
<section id="choix-du-modèle-final" class="level3">
<h3 class="anchored" data-anchor-id="choix-du-modèle-final">Choix du modèle final</h3>
<p>Compte tenu des résultats précédents, nous retenons le modèle issu de la sélection Stepwise sans le terme d’interaction comme notre modèle final expliquant l’indice de bonheur.</p>
</section>
</section>
<section id="diagnostics-des-résidus-sur-le-modèle-final" class="level2">
<h2 class="anchored" data-anchor-id="diagnostics-des-résidus-sur-le-modèle-final">Diagnostics des résidus sur le modèle final</h2>
<p>Vérifions maintenant la validité des hypothèses des MCO (citées en introduction) sur notre modèle final : <code>best_model</code>.</p>
<hr>
<center>
<div id="tab10" class="fig">
<p>Tableau 10 : Tableau de synthèse des diagnostics</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
====================================================
Test                             Statistique P_Value
----------------------------------------------------
Breusch-Pagan (Homoscédasticité)   5.1320    0.7434 
Shapiro-Wilk (Normalité)           0.9880    0.3435 
Durbin-Watson (Indépendance)       1.8850    0.2697 
----------------------------------------------------</code></pre>
</div>
</div>
</div>
</center>
<hr>
<p><strong>Interprétation des diagnostics :</strong> Les tests sont concluants et valident toutes les hypothèses des Moindres Carrés Ordinaires :</p>
<ul>
<li><p><strong>Homoscédasticité validée :</strong> Le test de Breusch-Pagan (p-value = <strong>0.7434</strong>) ne rejette pas l’hypothèse nulle. La variance des résidus est constante.</p></li>
<li><p><strong>Normalité validée :</strong> Le test de Shapiro-Wilk (p-value = <strong>0.3435</strong>) confirme que les résidus suivent une loi normale. L’inférence statistique (t-tests, intervalles de confiance) est donc fiable.</p></li>
<li><p><strong>Indépendance validée :</strong> Le test de Durbin-Watson (p-value = <strong>0.2697</strong>) ne détecte pas d’autocorrélation significative.</p></li>
</ul>
<section id="visualisation-des-diagnostics" class="level3">
<h3 class="anchored" data-anchor-id="visualisation-des-diagnostics">Visualisation des diagnostics</h3>
<div id="fig13" class="fig">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="rendu_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Figure 13 : Diagnostics visuels des résidus</p>
</div>
<p><strong>Analyse visuelle :</strong> Les graphiques confirment la robustesse du modèle.</p>
<ul>
<li><p><strong>Résidus vs Ajustés :</strong> Le nuage de points est dispersé aléatoirement autour de 0 sans forme marquée, ce qui corrobore l’homoscédasticité.</p></li>
<li><p><strong>Q-Q Plot :</strong> Les points s’alignent correctement sur la droite de normalité. On note quelques légers écarts aux extrémités correspondant à des pays comme <strong>Oman</strong> (résidu positif élevé) ou l’<strong>Afghanistan</strong> et le <strong>Botswana</strong> (résidus négatifs), mais ces <em>outliers</em> restent ponctuels et ne violent pas l’hypothèse de normalité globale.</p></li>
</ul>
</section>
<section id="conclusion-sur-les-corrections" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-sur-les-corrections">Conclusion sur les corrections</h3>
<p>Les diagnostics étant excellents, aucune correction (type White / HC1) n’est nécessaire. Nous pouvons interpréter directement les coefficients du modèle final.</p>
</section>
<section id="analyse-des-points-influents" class="level3">
<h3 class="anchored" data-anchor-id="analyse-des-points-influents">Analyse des points influents</h3>
<p>Nous complétons les diagnostics par une analyse des points influents (points leviers et outliers) qui pourraient biaiser l’estimation.</p>
<div id="fig14" class="fig">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="rendu_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Figure 14 : Détection des points influents (Distance de Cook et Effet Levier)</p>
</div>
<p><strong>Analyse des points influents :</strong> L’analyse de la distance de Cook met en évidence quatre pays : <strong>Oman</strong>, la <strong>Somalie,</strong> la <strong>Jordanie</strong> et le <strong>Botswana</strong> par ordre d’importance.</p>
<ul>
<li><p><strong>Distance de Cook :</strong> Bien que ces pays dépassent le seuil théorique de sensibilité (<span class="math inline">\(4/n \approx 0.03\)</span>), aucune observation ne s’approche du seuil critique de 0.5 ou 1. Ils influencent le modèle sans le déstabiliser.</p></li>
<li><p><strong>Levier vs Résidus :</strong> La <strong>Somalie</strong> se distingue par un fort effet de levier (probablement dû à sa valeur extrême en scolarisation, ou des valeurs manquantes trop lissées par notre pré traitement), mais son résidu reste modéré. <strong>Oman</strong>, le <strong>Botswana</strong> et la <strong>Jordanie</strong> ont des résidus plus importants, suggérant que le modèle explique moins bien leur niveau de bonheur spécifique. On peut supposer qu’il existe dans leurs cas des facteurs géopolitiques ou culturels non capturés par notre modèle.</p></li>
</ul>
<p>En conclusion, bien que ces pays atypiques existent, ils ne remettent pas en cause la validité globale du modèle.</p>
<hr>
<center>
<div id="tab11" class="fig">
<p>Tableau 11 : Résultats finaux du modèle économétrique</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
=====================================================
                              Dependent variable:    
                          ---------------------------
                                   Happiness         
-----------------------------------------------------
Political_Corruption            0.545** (0.248)      
log(GDP_per_Capita)            0.438*** (0.076)      
Lifespan                       0.042*** (0.011)      
Overweight_Adults               0.008* (0.004)       
Military_Expenses              -0.081** (0.033)      
Population_Growth              0.118*** (0.043)      
OCDE1                          0.396*** (0.148)      
Primary_School_Enrollment      -0.007** (0.003)      
Constant                        -1.484* (0.766)      
-----------------------------------------------------
Observations                          125            
R2                                   0.827           
Adjusted R2                          0.815           
Residual Std. Error            0.484 (df = 116)      
F Statistic                 69.122*** (df = 8; 116)  
=====================================================
Note:                     *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
</div>
</center>
<hr>
</section>
</section>
<section id="conclusion-et-discussion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion-et-discussion">Conclusion et discussion</h2>
<p>Notre analyse visait à déterminer les déterminants du bonheur (“Happiness”) à travers une régression linéaire multivariée sur un échantillon de 125 pays.</p>
<p><strong>Résultats principaux :</strong></p>
<ol type="1">
<li><strong>Richesse et Santé :</strong> Le PIB par habitant (en log) et l’espérance de vie sont les déterminants les plus puissants et positifs du bonheur. La relation logarithmique confirme que l’utilité marginale du revenu est décroissante : gagner 1000$ de plus apporte plus de bonheur dans un pays pauvre que dans un pays riche.</li>
<li><strong>Facteurs institutionnels :</strong> La corruption politique a un impact négatif significatif, tandis que l’appartenance à l’OCDE est souvent associée à un niveau de bonheur supérieur, toutes choses égales par ailleurs.</li>
<li><strong>Interaction non significative :</strong> Nos tests n’ont pas permis de valider statistiquement que l’effet de la richesse diffère significativement selon le niveau de développement (appartenance à l’OCDE). Le modèle simple reste le plus performant.</li>
<li><strong>Robustesse et Points influents :</strong> Les diagnostics (homoscédasticité, normalité) sont satisfaisants. L’analyse des points influents a identifié la Somalie (fort levier) et Oman (résidu élevé) comme des cas particuliers, mais leur impact reste limité et ne biaise pas les conclusions générales.</li>
<li><strong>Limites du modèle :</strong> Bien que les diagnostics soient globalement satisfaisants, des limites inhérentes aux données transversales subsistent.</li>
</ol>
<p><strong>Limites et Perspectives :</strong></p>
<ul>
<li><p><strong>Causalité :</strong> La corrélation n’implique pas la causalité. Est-ce que les gens heureux sont plus productifs (augmentant le PIB) ou l’inverse ?</p></li>
<li><p><strong>Variables omises :</strong> La culture, le climat, ou la liberté politique (différente de la corruption) pourraient jouer un rôle important.</p></li>
<li><p><strong>Données manquantes :</strong> L’exclusion de certains pays (Somalie, etc.) pour manque de données peut biaiser les résultats (biais de sélection).</p></li>
<li><p><strong>Perspectives :</strong> Pour aller plus loin, une analyse en panel (longitudinale) permettrait de contrôler les effets fixes par pays (culture, géographie) et de mieux saisir la dynamique temporelle du bonheur. L’ajout d’indicateurs d’inégalité (Gini) serait également pertinent.</p></li>
</ul>
</section>
</section>
<section id="bibliographie" class="level1">
<h1>Bibliographie</h1>
<ol type="1">
<li><strong>Easterlin, R. A.</strong> (1974). “Does Economic Growth Improve the Human Lot? Some Empirical Evidence”. <em>Nations and Households in Economic Growth</em>.</li>
<li><strong>Gallup World Poll</strong>. Methodology for the World Happiness Report.</li>
<li><strong>Kanto Fiaferana</strong>, <a href="https://pyrrhamide.github.io/regressions/reg-lin.html">Cours de régression linéaire</a></li>
<li><strong>Quarto</strong>, <a href="https://quarto.org/">Quarto</a></li>
<li>Ludovic C. &amp; mathandy, <a href="https://tex.stackexchange.com/questions/145657/align-equation-left">StackExchange</a></li>
<li><strong>Esteban Ortiz-Ospina, Max Roser</strong> (2013, last update: 2024). <a href="https://ourworldindata.org/happiness-and-life-satisfaction">Happiness and life satisfaction</a></li>
</ol>
<p><strong>Sources des données :</strong> - World Happiness Report (Happiness Score) - World Bank (GDP, Lifespan, Corruption, etc.) - Our World in Data (Energy, Military, Population)</p>
<p><strong>Utilisation d’outils d’intelligence artificielle :</strong> - GPT-mini-o5 - Gemini 3 Pro</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>